# Complete 200 achievement system from original Goal Quest

ALL_ACHIEVEMENTS = [
    # ========== STREAKS (1-25) ==========
    {"key": "streak_3", "title": "Getting Started", "description": "Maintain a 3-day streak", "icon": "🔥", "category": "streaks", "tier": "bronze", "xp_reward": 100, "gold_reward": 10},
    {"key": "streak_7", "title": "Week Warrior", "description": "Maintain a 7-day streak", "icon": "🔥", "category": "streaks", "tier": "bronze", "xp_reward": 250, "gold_reward": 25},
    {"key": "streak_14", "title": "Fortnight Fighter", "description": "Maintain a 14-day streak", "icon": "🔥", "category": "streaks", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "streak_21", "title": "Three Week Titan", "description": "Maintain a 21-day streak", "icon": "🔥", "category": "streaks", "tier": "silver", "xp_reward": 750, "gold_reward": 75},
    {"key": "streak_30", "title": "Monthly Master", "description": "Maintain a 30-day streak", "icon": "🔥", "category": "streaks", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "streak_45", "title": "Iron Will", "description": "Maintain a 45-day streak", "icon": "🔥", "category": "streaks", "tier": "gold", "xp_reward": 1500, "gold_reward": 150},
    {"key": "streak_60", "title": "Diamond Discipline", "description": "Maintain a 60-day streak", "icon": "🔥", "category": "streaks", "tier": "platinum", "xp_reward": 2000, "gold_reward": 200, "stat_bonus": '{"stat": "willpower", "amount": 5}'},
    {"key": "streak_90", "title": "Quarterly Champion", "description": "Maintain a 90-day streak", "icon": "🔥", "category": "streaks", "tier": "platinum", "xp_reward": 3000, "gold_reward": 300, "stat_bonus": '{"stat": "willpower", "amount": 10}'},
    {"key": "streak_180", "title": "Half-Year Hero", "description": "Maintain a 180-day streak", "icon": "🔥", "category": "streaks", "tier": "legendary", "xp_reward": 5000, "gold_reward": 500, "stat_bonus": '{"stat": "willpower", "amount": 15}', "special_power": "Double XP on weekends"},
    {"key": "streak_365", "title": "Year of Power", "description": "Maintain a 365-day streak", "icon": "👑", "category": "streaks", "tier": "legendary", "xp_reward": 10000, "gold_reward": 1000, "stat_bonus": '{"stat": "willpower", "amount": 25}', "special_power": "Permanent 10% XP boost"},
    {"key": "comeback_3", "title": "Rising Again", "description": "Recover a 3-day streak after breaking", "icon": "🔄", "category": "streaks", "tier": "bronze", "xp_reward": 150, "gold_reward": 15},
    {"key": "comeback_7", "title": "Phoenix Rising", "description": "Recover a 7-day streak after breaking", "icon": "🔄", "category": "streaks", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "comeback_30", "title": "Unstoppable Force", "description": "Recover a 30-day streak after breaking", "icon": "🔄", "category": "streaks", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "streak_multi_3", "title": "Multi-Tasker", "description": "Maintain 3 habits with 7+ day streaks", "icon": "📚", "category": "streaks", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "streak_multi_5", "title": "Habit Master", "description": "Maintain 5 habits with 7+ day streaks", "icon": "📚", "category": "streaks", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "streak_multi_10", "title": "Discipline Incarnate", "description": "Maintain 10 habits with 7+ day streaks", "icon": "📚", "category": "streaks", "tier": "legendary", "xp_reward": 2500, "gold_reward": 250, "stat_bonus": '{"stat": "agility", "amount": 10}'},
    {"key": "weekend_warrior", "title": "Weekend Warrior", "description": "Complete habits every weekend for a month", "icon": "📅", "category": "streaks", "tier": "silver", "xp_reward": 600, "gold_reward": 60},
    {"key": "early_bird_7", "title": "Early Bird", "description": "Complete a habit before 7AM for 7 days", "icon": "🌅", "category": "streaks", "tier": "silver", "xp_reward": 400, "gold_reward": 40, "stat_bonus": '{"stat": "vitality", "amount": 3}'},
    {"key": "night_owl_7", "title": "Night Owl", "description": "Complete a habit after 10PM for 7 days", "icon": "🌙", "category": "streaks", "tier": "silver", "xp_reward": 400, "gold_reward": 40, "stat_bonus": '{"stat": "sense", "amount": 3}'},
    {"key": "perfect_week", "title": "Perfect Week", "description": "Complete all habits for 7 consecutive days", "icon": "✅", "category": "streaks", "tier": "gold", "xp_reward": 1200, "gold_reward": 120},
    {"key": "perfect_month", "title": "Perfect Month", "description": "Complete all habits for 30 consecutive days", "icon": "✅", "category": "streaks", "tier": "legendary", "xp_reward": 5000, "gold_reward": 500, "stat_bonus": '{"stat": "willpower", "amount": 20}', "special_power": "Unlock exclusive avatar frame"},
    {"key": "consistency_king", "title": "Consistency King", "description": "90% completion rate for 30 days", "icon": "📈", "category": "streaks", "tier": "gold", "xp_reward": 1500, "gold_reward": 150},
    {"key": "no_breaks", "title": "No Breaks", "description": "Don't skip any scheduled habits for 14 days", "icon": "🛡️", "category": "streaks", "tier": "silver", "xp_reward": 700, "gold_reward": 70},
    {"key": "daily_grind_100", "title": "Daily Grind", "description": "Complete 100 total habit check-ins", "icon": "⚡", "category": "streaks", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "daily_grind_500", "title": "Relentless", "description": "Complete 500 total habit check-ins", "icon": "⚡", "category": "streaks", "tier": "gold", "xp_reward": 1500, "gold_reward": 150},

    # ========== LEVELS (26-50) ==========
    {"key": "level_5", "title": "Rising Star", "description": "Reach Level 5", "icon": "⭐", "category": "levels", "tier": "bronze", "xp_reward": 500, "gold_reward": 50},
    {"key": "level_10", "title": "Seasoned Adventurer", "description": "Reach Level 10", "icon": "⭐", "category": "levels", "tier": "silver", "xp_reward": 1000, "gold_reward": 100},
    {"key": "level_15", "title": "Veteran", "description": "Reach Level 15", "icon": "⭐", "category": "levels", "tier": "silver", "xp_reward": 1500, "gold_reward": 150},
    {"key": "level_20", "title": "Expert", "description": "Reach Level 20", "icon": "👑", "category": "levels", "tier": "gold", "xp_reward": 2000, "gold_reward": 200},
    {"key": "level_25", "title": "Elite Champion", "description": "Reach Level 25", "icon": "👑", "category": "levels", "tier": "gold", "xp_reward": 2500, "gold_reward": 250},
    {"key": "level_30", "title": "Master", "description": "Reach Level 30", "icon": "👑", "category": "levels", "tier": "gold", "xp_reward": 3000, "gold_reward": 300, "stat_bonus": '{"stat": "intelligence", "amount": 5}'},
    {"key": "level_40", "title": "Grandmaster", "description": "Reach Level 40", "icon": "🛡️", "category": "levels", "tier": "platinum", "xp_reward": 4000, "gold_reward": 400, "stat_bonus": '{"stat": "strength", "amount": 5}'},
    {"key": "level_50", "title": "Legendary Hero", "description": "Reach Level 50", "icon": "🛡️", "category": "levels", "tier": "platinum", "xp_reward": 5000, "gold_reward": 500, "stat_bonus": '{"stat": "vitality", "amount": 10}', "special_power": "Unlock S-Rank missions"},
    {"key": "level_60", "title": "Mythic Guardian", "description": "Reach Level 60", "icon": "⚔️", "category": "levels", "tier": "platinum", "xp_reward": 6000, "gold_reward": 600, "stat_bonus": '{"stat": "agility", "amount": 10}'},
    {"key": "level_70", "title": "Titan", "description": "Reach Level 70", "icon": "⚔️", "category": "levels", "tier": "platinum", "xp_reward": 7000, "gold_reward": 700, "stat_bonus": '{"stat": "sense", "amount": 10}'},
    {"key": "level_80", "title": "Demigod", "description": "Reach Level 80", "icon": "⚔️", "category": "levels", "tier": "legendary", "xp_reward": 8000, "gold_reward": 800, "stat_bonus": '{"stat": "willpower", "amount": 15}'},
    {"key": "level_90", "title": "Ascended", "description": "Reach Level 90", "icon": "✨", "category": "levels", "tier": "legendary", "xp_reward": 9000, "gold_reward": 900, "stat_bonus": '{"stat": "intelligence", "amount": 15}'},
    {"key": "level_100", "title": "Transcendent", "description": "Reach Level 100", "icon": "✨", "category": "levels", "tier": "legendary", "xp_reward": 10000, "gold_reward": 1000, "stat_bonus": '{"stat": "strength", "amount": 20}', "special_power": "Unlock Prestige system"},
    {"key": "fast_level_10", "title": "Quick Learner", "description": "Reach level 10 in 7 days", "icon": "⚡", "category": "levels", "tier": "silver", "xp_reward": 800, "gold_reward": 80},
    {"key": "fast_level_25", "title": "Speed Demon", "description": "Reach level 25 in 30 days", "icon": "⚡", "category": "levels", "tier": "gold", "xp_reward": 2000, "gold_reward": 200},
    {"key": "xp_day_1000", "title": "Productive Day", "description": "Earn 1,000 XP in one day", "icon": "💫", "category": "levels", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "xp_day_5000", "title": "Epic Day", "description": "Earn 5,000 XP in one day", "icon": "💫", "category": "levels", "tier": "gold", "xp_reward": 1500, "gold_reward": 150},
    {"key": "xp_week_10000", "title": "Legendary Week", "description": "Earn 10,000 XP in one week", "icon": "💫", "category": "levels", "tier": "platinum", "xp_reward": 2500, "gold_reward": 250},
    {"key": "rank_skilled", "title": "Skilled Hunter", "description": "Achieve Skilled Hunter rank", "icon": "🎖️", "category": "levels", "tier": "silver", "xp_reward": 600, "gold_reward": 60},
    {"key": "rank_elite", "title": "Elite Hunter", "description": "Achieve Elite Hunter rank", "icon": "🎖️", "category": "levels", "tier": "gold", "xp_reward": 1200, "gold_reward": 120},
    {"key": "rank_srank", "title": "S-Rank Hunter", "description": "Achieve S-Rank Hunter status", "icon": "🎖️", "category": "levels", "tier": "legendary", "xp_reward": 3000, "gold_reward": 300, "special_power": "S-Rank badge on profile"},

    # ========== HABITS (51-90) ==========
    {"key": "first_habit", "title": "Habit Former", "description": "Create your first habit", "icon": "⚡", "category": "habits", "tier": "bronze", "xp_reward": 100, "gold_reward": 10},
    {"key": "habits_5", "title": "Building Foundation", "description": "Create 5 habits", "icon": "📚", "category": "habits", "tier": "bronze", "xp_reward": 250, "gold_reward": 25},
    {"key": "habits_10", "title": "Habit Collector", "description": "Create 10 habits", "icon": "📚", "category": "habits", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "habits_15", "title": "Habit Enthusiast", "description": "Create 15 habits", "icon": "📚", "category": "habits", "tier": "silver", "xp_reward": 750, "gold_reward": 75},
    {"key": "habits_20", "title": "Habit Architect", "description": "Create 20 habits", "icon": "📚", "category": "habits", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "habits_30", "title": "Habit Master", "description": "Create 30 habits", "icon": "📚", "category": "habits", "tier": "platinum", "xp_reward": 1500, "gold_reward": 150, "stat_bonus": '{"stat": "intelligence", "amount": 5}'},
    {"key": "first_complete", "title": "First Step", "description": "Complete your first habit", "icon": "✅", "category": "habits", "tier": "bronze", "xp_reward": 50, "gold_reward": 5},
    {"key": "complete_10", "title": "Getting Momentum", "description": "Complete habits 10 times", "icon": "✅", "category": "habits", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "complete_50", "title": "Building Routine", "description": "Complete habits 50 times", "icon": "✅", "category": "habits", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "complete_100", "title": "Century Mark", "description": "Complete habits 100 times", "icon": "✅", "category": "habits", "tier": "silver", "xp_reward": 800, "gold_reward": 80},
    {"key": "complete_250", "title": "Quarter Thousand", "description": "Complete habits 250 times", "icon": "✅", "category": "habits", "tier": "gold", "xp_reward": 1200, "gold_reward": 120},
    {"key": "complete_500", "title": "Half Millennium", "description": "Complete habits 500 times", "icon": "✅", "category": "habits", "tier": "gold", "xp_reward": 2000, "gold_reward": 200},
    {"key": "complete_1000", "title": "Thousand Strong", "description": "Complete habits 1,000 times", "icon": "✅", "category": "habits", "tier": "platinum", "xp_reward": 4000, "gold_reward": 400, "stat_bonus": '{"stat": "vitality", "amount": 10}'},
    {"key": "complete_5000", "title": "Habit Legend", "description": "Complete habits 5,000 times", "icon": "✅", "category": "habits", "tier": "legendary", "xp_reward": 10000, "gold_reward": 1000, "special_power": "Legendary completion animation"},
    {"key": "hard_habit_1", "title": "Challenge Accepted", "description": "Complete a hard difficulty habit", "icon": "⚔️", "category": "habits", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "hard_habit_10", "title": "Challenge Seeker", "description": "Complete 10 hard habits", "icon": "⚔️", "category": "habits", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "hard_habit_50", "title": "Challenge Master", "description": "Complete 50 hard habits", "icon": "⚔️", "category": "habits", "tier": "gold", "xp_reward": 1500, "gold_reward": 150, "stat_bonus": '{"stat": "strength", "amount": 5}'},
    {"key": "hard_habit_100", "title": "Challenge Conqueror", "description": "Complete 100 hard habits", "icon": "⚔️", "category": "habits", "tier": "platinum", "xp_reward": 3000, "gold_reward": 300, "stat_bonus": '{"stat": "strength", "amount": 10}'},
    {"key": "category_fitness", "title": "Fitness Devotee", "description": "Complete 50 fitness habits", "icon": "💪", "category": "habits", "tier": "silver", "xp_reward": 600, "gold_reward": 60, "stat_bonus": '{"stat": "strength", "amount": 5}'},
    {"key": "category_health", "title": "Health Guardian", "description": "Complete 50 health habits", "icon": "❤️", "category": "habits", "tier": "silver", "xp_reward": 600, "gold_reward": 60, "stat_bonus": '{"stat": "vitality", "amount": 5}'},
    {"key": "category_learning", "title": "Knowledge Seeker", "description": "Complete 50 learning habits", "icon": "📖", "category": "habits", "tier": "silver", "xp_reward": 600, "gold_reward": 60, "stat_bonus": '{"stat": "intelligence", "amount": 5}'},
    {"key": "category_mindfulness", "title": "Inner Peace", "description": "Complete 50 mindfulness habits", "icon": "🧘", "category": "habits", "tier": "silver", "xp_reward": 600, "gold_reward": 60, "stat_bonus": '{"stat": "sense", "amount": 5}'},
    {"key": "category_productivity", "title": "Efficiency Expert", "description": "Complete 50 productivity habits", "icon": "⚡", "category": "habits", "tier": "silver", "xp_reward": 600, "gold_reward": 60, "stat_bonus": '{"stat": "agility", "amount": 5}'},
    {"key": "perfect_day", "title": "Perfect Day", "description": "Complete all habits in a single day", "icon": "✨", "category": "habits", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "perfect_day_5", "title": "Flawless Five", "description": "Achieve 5 perfect days", "icon": "✨", "category": "habits", "tier": "gold", "xp_reward": 2000, "gold_reward": 200},
    {"key": "perfect_day_30", "title": "Perfection Incarnate", "description": "Achieve 30 perfect days", "icon": "✨", "category": "habits", "tier": "legendary", "xp_reward": 8000, "gold_reward": 800, "special_power": "Perfect day crown animation"},
    {"key": "diversity_3", "title": "Well-Rounded", "description": "Complete habits in 3 different categories today", "icon": "🔄", "category": "habits", "tier": "bronze", "xp_reward": 150, "gold_reward": 15},
    {"key": "diversity_5", "title": "Renaissance Soul", "description": "Complete habits in 5 different categories today", "icon": "🔄", "category": "habits", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "priority_master", "title": "Priority Master", "description": "Complete all priority habits for 7 days", "icon": "⭐", "category": "habits", "tier": "silver", "xp_reward": 700, "gold_reward": 70},
    {"key": "habit_veteran", "title": "Habit Veteran", "description": "Keep the same habit active for 90 days", "icon": "🕐", "category": "habits", "tier": "gold", "xp_reward": 1500, "gold_reward": 150},
    {"key": "habit_ancient", "title": "Ancient Wisdom", "description": "Keep the same habit active for 365 days", "icon": "🕐", "category": "habits", "tier": "legendary", "xp_reward": 5000, "gold_reward": 500, "special_power": "Ancient habit badge"},
    {"key": "quick_complete", "title": "Speed Runner", "description": "Complete 5 habits within 1 hour", "icon": "⏱️", "category": "habits", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "balanced_life", "title": "Balanced Life", "description": "Have habits in all 6 categories", "icon": "⚖️", "category": "habits", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "weekday_warrior", "title": "Weekday Warrior", "description": "Complete all weekday habits for 4 weeks", "icon": "📅", "category": "habits", "tier": "gold", "xp_reward": 1200, "gold_reward": 120},
    {"key": "custom_schedule", "title": "Schedule Master", "description": "Create 5 habits with custom schedules", "icon": "📆", "category": "habits", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "reminder_guru", "title": "Reminder Guru", "description": "Set up reminders for 10 habits", "icon": "🔔", "category": "habits", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "color_coded", "title": "Color Coordinated", "description": "Assign colors to 10 habits", "icon": "🎨", "category": "habits", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "description_writer", "title": "Detail Oriented", "description": "Add descriptions to 10 habits", "icon": "📝", "category": "habits", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "active_manager", "title": "Active Manager", "description": "Deactivate and reactivate a habit", "icon": "🔄", "category": "habits", "tier": "bronze", "xp_reward": 100, "gold_reward": 10},

    # ========== GOALS (91-130) ==========
    {"key": "first_goal", "title": "Goal Setter", "description": "Create your first goal", "icon": "🎯", "category": "goals", "tier": "bronze", "xp_reward": 150, "gold_reward": 15},
    {"key": "goals_5", "title": "Ambitious", "description": "Create 5 goals", "icon": "🎯", "category": "goals", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "goals_10", "title": "Visionary", "description": "Create 10 goals", "icon": "🎯", "category": "goals", "tier": "gold", "xp_reward": 800, "gold_reward": 80},
    {"key": "goals_25", "title": "Dream Architect", "description": "Create 25 goals", "icon": "🎯", "category": "goals", "tier": "platinum", "xp_reward": 1500, "gold_reward": 150},
    {"key": "goal_complete_1", "title": "Achiever", "description": "Complete your first goal", "icon": "🏆", "category": "goals", "tier": "bronze", "xp_reward": 300, "gold_reward": 30},
    {"key": "goal_complete_5", "title": "Goal Crusher", "description": "Complete 5 goals", "icon": "🏆", "category": "goals", "tier": "silver", "xp_reward": 750, "gold_reward": 75},
    {"key": "goal_complete_10", "title": "Ambitious Achiever", "description": "Complete 10 goals", "icon": "🏆", "category": "goals", "tier": "gold", "xp_reward": 1500, "gold_reward": 150},
    {"key": "goal_complete_25", "title": "Dream Realizer", "description": "Complete 25 goals", "icon": "🏆", "category": "goals", "tier": "platinum", "xp_reward": 3500, "gold_reward": 350, "stat_bonus": '{"stat": "intelligence", "amount": 10}'},
    {"key": "goal_complete_50", "title": "Life Transformer", "description": "Complete 50 goals", "icon": "🏆", "category": "goals", "tier": "legendary", "xp_reward": 7500, "gold_reward": 750, "special_power": "Goal mastery crown"},
    {"key": "hard_goal_1", "title": "Big Dreamer", "description": "Complete a hard difficulty goal", "icon": "⛰️", "category": "goals", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "hard_goal_5", "title": "Mountain Climber", "description": "Complete 5 hard goals", "icon": "⛰️", "category": "goals", "tier": "gold", "xp_reward": 1500, "gold_reward": 150},
    {"key": "hard_goal_10", "title": "Peak Conqueror", "description": "Complete 10 hard goals", "icon": "⛰️", "category": "goals", "tier": "platinum", "xp_reward": 3000, "gold_reward": 300, "stat_bonus": '{"stat": "willpower", "amount": 10}'},
    {"key": "step_complete_10", "title": "Step by Step", "description": "Complete 10 goal steps", "icon": "✓", "category": "goals", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "step_complete_50", "title": "Methodical", "description": "Complete 50 goal steps", "icon": "✓", "category": "goals", "tier": "silver", "xp_reward": 600, "gold_reward": 60},
    {"key": "step_complete_100", "title": "Process Master", "description": "Complete 100 goal steps", "icon": "✓", "category": "goals", "tier": "gold", "xp_reward": 1200, "gold_reward": 120},
    {"key": "on_time_1", "title": "Punctual", "description": "Complete a goal before deadline", "icon": "🕐", "category": "goals", "tier": "bronze", "xp_reward": 250, "gold_reward": 25},
    {"key": "on_time_5", "title": "Time Keeper", "description": "Complete 5 goals before deadline", "icon": "🕐", "category": "goals", "tier": "silver", "xp_reward": 700, "gold_reward": 70},
    {"key": "on_time_10", "title": "Deadline Master", "description": "Complete 10 goals before deadline", "icon": "🕐", "category": "goals", "tier": "gold", "xp_reward": 1400, "gold_reward": 140},
    {"key": "early_bird_goal", "title": "Early Finisher", "description": "Complete a goal a week early", "icon": "🚀", "category": "goals", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "month_achiever", "title": "Monthly Achiever", "description": "Complete a goal in under 30 days", "icon": "📅", "category": "goals", "tier": "silver", "xp_reward": 600, "gold_reward": 60},
    {"key": "year_planner", "title": "Year Planner", "description": "Set a goal with a 1-year deadline", "icon": "📆", "category": "goals", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "priority_goals", "title": "Priority Focused", "description": "Complete 5 priority goals", "icon": "⭐", "category": "goals", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "goal_chain_3", "title": "Chain Reaction", "description": "Complete 3 progressive goals in a row", "icon": "🔗", "category": "goals", "tier": "gold", "xp_reward": 1500, "gold_reward": 150},
    {"key": "goal_chain_5", "title": "Unstoppable Progress", "description": "Complete 5 progressive goals", "icon": "🔗", "category": "goals", "tier": "platinum", "xp_reward": 2500, "gold_reward": 250},
    {"key": "ai_goal_1", "title": "AI Collaborator", "description": "Complete an AI-generated goal", "icon": "🤖", "category": "goals", "tier": "bronze", "xp_reward": 300, "gold_reward": 30},
    {"key": "ai_goal_5", "title": "AI Partner", "description": "Complete 5 AI-generated goals", "icon": "🤖", "category": "goals", "tier": "silver", "xp_reward": 800, "gold_reward": 80},
    {"key": "full_progress", "title": "Full Progress", "description": "Update a goal from 0% to 100%", "icon": "📈", "category": "goals", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "goal_steps_5", "title": "Planner", "description": "Create a goal with 5+ steps", "icon": "📋", "category": "goals", "tier": "bronze", "xp_reward": 150, "gold_reward": 15},
    {"key": "goal_steps_10", "title": "Master Planner", "description": "Create a goal with 10+ steps", "icon": "📋", "category": "goals", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "multi_category_goals", "title": "Diverse Goals", "description": "Complete goals in 5 different categories", "icon": "🎨", "category": "goals", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "goal_spree", "title": "Goal Spree", "description": "Complete 3 goals in one week", "icon": "🔥", "category": "goals", "tier": "gold", "xp_reward": 1200, "gold_reward": 120},
    {"key": "long_term_1", "title": "Long-Term Thinker", "description": "Complete a goal set 6+ months ago", "icon": "⏳", "category": "goals", "tier": "gold", "xp_reward": 1500, "gold_reward": 150},
    {"key": "progressive_master", "title": "Progressive Master", "description": "Complete 10 progressive follow-up goals", "icon": "↗️", "category": "goals", "tier": "legendary", "xp_reward": 5000, "gold_reward": 500, "special_power": "Automatic goal difficulty scaling"},
    {"key": "habit_from_goal", "title": "Habit Creator", "description": "Create a habit from a goal suggestion", "icon": "🔄", "category": "goals", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "fitness_goal", "title": "Fitness Achiever", "description": "Complete 5 fitness goals", "icon": "💪", "category": "goals", "tier": "silver", "xp_reward": 700, "gold_reward": 70, "stat_bonus": '{"stat": "strength", "amount": 5}'},
    {"key": "learning_goal", "title": "Knowledge Achiever", "description": "Complete 5 learning goals", "icon": "🎓", "category": "goals", "tier": "silver", "xp_reward": 700, "gold_reward": 70, "stat_bonus": '{"stat": "intelligence", "amount": 5}'},
    {"key": "personal_goal", "title": "Self-Improvement", "description": "Complete 5 personal goals", "icon": "👤", "category": "goals", "tier": "silver", "xp_reward": 700, "gold_reward": 70, "stat_bonus": '{"stat": "willpower", "amount": 5}'},
    {"key": "work_goal", "title": "Career Builder", "description": "Complete 5 work goals", "icon": "💼", "category": "goals", "tier": "silver", "xp_reward": 700, "gold_reward": 70, "stat_bonus": '{"stat": "agility", "amount": 5}'},
    {"key": "health_goal", "title": "Health Champion", "description": "Complete 5 health goals", "icon": "❤️", "category": "goals", "tier": "silver", "xp_reward": 700, "gold_reward": 70, "stat_bonus": '{"stat": "vitality", "amount": 5}'},

    # ========== SPECIAL (131-160) ==========
    {"key": "first_login", "title": "Welcome", "description": "Log in for the first time", "icon": "👋", "category": "special", "tier": "bronze", "xp_reward": 50, "gold_reward": 5},
    {"key": "profile_complete", "title": "Identity Established", "description": "Complete your profile", "icon": "👤", "category": "special", "tier": "bronze", "xp_reward": 100, "gold_reward": 10},
    {"key": "first_note", "title": "Journal Keeper", "description": "Create your first note", "icon": "📝", "category": "special", "tier": "bronze", "xp_reward": 50, "gold_reward": 5},
    {"key": "notes_10", "title": "Thoughtful Writer", "description": "Create 10 notes", "icon": "📝", "category": "special", "tier": "silver", "xp_reward": 300, "gold_reward": 30},
    {"key": "ai_summary", "title": "AI Assisted", "description": "Use AI to summarize a note", "icon": "🤖", "category": "special", "tier": "bronze", "xp_reward": 100, "gold_reward": 10},
    {"key": "shop_purchase", "title": "First Purchase", "description": "Buy your first item from the shop", "icon": "🛒", "category": "special", "tier": "bronze", "xp_reward": 100, "gold_reward": 10},
    {"key": "shop_spender", "title": "Big Spender", "description": "Spend 10,000 gold in the shop", "icon": "💰", "category": "special", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "equipment_first", "title": "Geared Up", "description": "Equip your first item", "icon": "⚔️", "category": "special", "tier": "bronze", "xp_reward": 150, "gold_reward": 15},
    {"key": "full_set", "title": "Complete Arsenal", "description": "Have items equipped in all slots", "icon": "🛡️", "category": "special", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "legendary_item", "title": "Legendary Collector", "description": "Own a legendary item", "icon": "👑", "category": "special", "tier": "legendary", "xp_reward": 2000, "gold_reward": 200},
    {"key": "philosophy_upload", "title": "Personal Library", "description": "Upload your first philosophy document", "icon": "📚", "category": "special", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "philosophy_5", "title": "Wisdom Collector", "description": "Upload 5 philosophy documents", "icon": "📚", "category": "special", "tier": "silver", "xp_reward": 600, "gold_reward": 60},
    {"key": "daily_login_7", "title": "Committed", "description": "Log in for 7 consecutive days", "icon": "📅", "category": "special", "tier": "bronze", "xp_reward": 300, "gold_reward": 30},
    {"key": "daily_login_30", "title": "Dedicated", "description": "Log in for 30 consecutive days", "icon": "📅", "category": "special", "tier": "silver", "xp_reward": 800, "gold_reward": 80},
    {"key": "daily_login_100", "title": "Devoted", "description": "Log in for 100 consecutive days", "icon": "📅", "category": "special", "tier": "gold", "xp_reward": 2000, "gold_reward": 200},
    {"key": "morning_person", "title": "Morning Person", "description": "Log in before 8AM for 7 days", "icon": "🌅", "category": "special", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "night_person", "title": "Night Person", "description": "Log in after 10PM for 7 days", "icon": "🌙", "category": "special", "tier": "silver", "xp_reward": 400, "gold_reward": 40},
    {"key": "weekend_check", "title": "Weekend Warrior", "description": "Check in on both Saturday and Sunday", "icon": "📅", "category": "special", "tier": "bronze", "xp_reward": 150, "gold_reward": 15},

    # ========== STATS (161-190) ==========
    {"key": "strength_10", "title": "Strong", "description": "Reach 10 Strength", "icon": "⚔️", "category": "stats", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "strength_25", "title": "Mighty", "description": "Reach 25 Strength", "icon": "⚔️", "category": "stats", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "strength_50", "title": "Powerful", "description": "Reach 50 Strength", "icon": "⚔️", "category": "stats", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "strength_100", "title": "Titan Strength", "description": "Reach 100 Strength", "icon": "⚔️", "category": "stats", "tier": "legendary", "xp_reward": 2500, "gold_reward": 250, "special_power": "Strength training bonus XP"},
    {"key": "intelligence_10", "title": "Clever", "description": "Reach 10 Intelligence", "icon": "🧠", "category": "stats", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "intelligence_25", "title": "Wise", "description": "Reach 25 Intelligence", "icon": "🧠", "category": "stats", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "intelligence_50", "title": "Brilliant", "description": "Reach 50 Intelligence", "icon": "🧠", "category": "stats", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "intelligence_100", "title": "Genius", "description": "Reach 100 Intelligence", "icon": "🧠", "category": "stats", "tier": "legendary", "xp_reward": 2500, "gold_reward": 250, "special_power": "Learning bonus XP"},
    {"key": "vitality_10", "title": "Healthy", "description": "Reach 10 Vitality", "icon": "❤️", "category": "stats", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "vitality_25", "title": "Robust", "description": "Reach 25 Vitality", "icon": "❤️", "category": "stats", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "vitality_50", "title": "Resilient", "description": "Reach 50 Vitality", "icon": "❤️", "category": "stats", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "vitality_100", "title": "Indomitable", "description": "Reach 100 Vitality", "icon": "❤️", "category": "stats", "tier": "legendary", "xp_reward": 2500, "gold_reward": 250, "special_power": "Health bonus XP"},
    {"key": "agility_10", "title": "Quick", "description": "Reach 10 Agility", "icon": "⚡", "category": "stats", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "agility_25", "title": "Swift", "description": "Reach 25 Agility", "icon": "⚡", "category": "stats", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "agility_50", "title": "Lightning", "description": "Reach 50 Agility", "icon": "⚡", "category": "stats", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "agility_100", "title": "Flash", "description": "Reach 100 Agility", "icon": "⚡", "category": "stats", "tier": "legendary", "xp_reward": 2500, "gold_reward": 250, "special_power": "Productivity bonus XP"},
    {"key": "sense_10", "title": "Aware", "description": "Reach 10 Sense", "icon": "👁️", "category": "stats", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "sense_25", "title": "Perceptive", "description": "Reach 25 Sense", "icon": "👁️", "category": "stats", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "sense_50", "title": "Clairvoyant", "description": "Reach 50 Sense", "icon": "👁️", "category": "stats", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "sense_100", "title": "Omniscient", "description": "Reach 100 Sense", "icon": "👁️", "category": "stats", "tier": "legendary", "xp_reward": 2500, "gold_reward": 250, "special_power": "Sense-related bonus XP"},
    {"key": "willpower_10", "title": "Determined", "description": "Reach 10 Willpower", "icon": "🔥", "category": "stats", "tier": "bronze", "xp_reward": 200, "gold_reward": 20},
    {"key": "willpower_25", "title": "Resolute", "description": "Reach 25 Willpower", "icon": "🔥", "category": "stats", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "willpower_50", "title": "Unbreakable", "description": "Reach 50 Willpower", "icon": "🔥", "category": "stats", "tier": "gold", "xp_reward": 1000, "gold_reward": 100},
    {"key": "willpower_100", "title": "Iron Will", "description": "Reach 100 Willpower", "icon": "🔥", "category": "stats", "tier": "legendary", "xp_reward": 2500, "gold_reward": 250, "special_power": "Willpower bonus XP"},
    {"key": "balanced_stats_10", "title": "Balanced Beginner", "description": "All stats at 10+", "icon": "⚖️", "category": "stats", "tier": "silver", "xp_reward": 800, "gold_reward": 80},
    {"key": "balanced_stats_25", "title": "Balanced Warrior", "description": "All stats at 25+", "icon": "⚖️", "category": "stats", "tier": "gold", "xp_reward": 2000, "gold_reward": 200},
    {"key": "balanced_stats_50", "title": "Perfect Balance", "description": "All stats at 50+", "icon": "⚖️", "category": "stats", "tier": "platinum", "xp_reward": 5000, "gold_reward": 500, "stat_bonus": '{"stat": "willpower", "amount": 15}'},
    {"key": "balanced_stats_100", "title": "True Mastery", "description": "All stats at 100+", "icon": "👑", "category": "stats", "tier": "legendary", "xp_reward": 15000, "gold_reward": 1500, "special_power": "Universal 5% XP boost"},
    {"key": "stat_total_100", "title": "Growing Power", "description": "Reach 100 total stat points", "icon": "📈", "category": "stats", "tier": "silver", "xp_reward": 500, "gold_reward": 50},
    {"key": "stat_total_500", "title": "Formidable", "description": "Reach 500 total stat points", "icon": "📈", "category": "stats", "tier": "platinum", "xp_reward": 2500, "gold_reward": 250},

    # ========== LEGENDARY (191-200) ==========
    {"key": "ultimate_hunter", "title": "Ultimate Hunter", "description": "Unlock 50 achievements", "icon": "🏅", "category": "legendary", "tier": "legendary", "xp_reward": 5000, "gold_reward": 500, "special_power": "Achievement hunter badge"},
    {"key": "achievement_master", "title": "Achievement Master", "description": "Unlock 100 achievements", "icon": "🏅", "category": "legendary", "tier": "legendary", "xp_reward": 10000, "gold_reward": 1000, "special_power": "Master collector frame"},
    {"key": "completionist", "title": "Completionist", "description": "Unlock 150 achievements", "icon": "🏅", "category": "legendary", "tier": "legendary", "xp_reward": 20000, "gold_reward": 2000, "special_power": "Completionist title"},
    {"key": "legend", "title": "Living Legend", "description": "Unlock all 200 achievements", "icon": "👑", "category": "legendary", "tier": "legendary", "xp_reward": 50000, "gold_reward": 5000, "stat_bonus": '{"stat": "willpower", "amount": 50}', "special_power": "Legendary status - Ultimate power unlocked"},
    {"key": "year_one", "title": "Year One", "description": "Use the app for a full year", "icon": "📅", "category": "legendary", "tier": "legendary", "xp_reward": 10000, "gold_reward": 1000, "special_power": "Anniversary badge"},
    {"key": "shadow_monarch", "title": "True Shadow Monarch", "description": "Reach Level 100 with all stats at 100", "icon": "👑", "category": "legendary", "tier": "legendary", "xp_reward": 25000, "gold_reward": 2500, "special_power": "Shadow Monarch powers unlocked"},
    {"key": "perfect_year", "title": "Perfect Year", "description": "365 perfect days", "icon": "✨", "category": "legendary", "tier": "legendary", "xp_reward": 50000, "gold_reward": 5000, "special_power": "Golden year aura"},
    {"key": "million_xp", "title": "Million XP Club", "description": "Earn 1,000,000 total XP", "icon": "⭐", "category": "legendary", "tier": "legendary", "xp_reward": 25000, "gold_reward": 2500, "special_power": "Million XP particle effects"},
    {"key": "habit_legend", "title": "Habit Legend", "description": "10,000 habit completions", "icon": "🔥", "category": "legendary", "tier": "legendary", "xp_reward": 25000, "gold_reward": 2500, "special_power": "Legendary habit animation"},
    {"key": "enlightened", "title": "Enlightened One", "description": "Max level, all achievements, perfect balance", "icon": "☀️", "category": "legendary", "tier": "legendary", "xp_reward": 100000, "gold_reward": 10000, "stat_bonus": '{"stat": "sense", "amount": 100}', "special_power": "Enlightenment - transcend limits"},
]

def initialize_achievements(db):
    """Initialize all 200 achievements in the database"""
    conn = db.get_connection()
    c = conn.cursor()
    
    for ach in ALL_ACHIEVEMENTS:
        try:
            c.execute("""
                INSERT OR IGNORE INTO achievements 
                (key, title, description, icon, category, tier, xp_reward, gold_reward, stat_bonus, special_power)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                ach["key"],
                ach["title"],
                ach["description"],
                ach["icon"],
                ach["category"],
                ach["tier"],
                ach["xp_reward"],
                ach["gold_reward"],
                ach.get("stat_bonus"),
                ach.get("special_power")
            ))
        except Exception as e:
            print(f"Error initializing achievement {ach['key']}: {e}")
    
    conn.commit()
